function Hd = cp_CarusoResponseFilter
    %CP_CARUSORESPONSEFILTER Returns a discrete-time filter object.
    
    %
    % MATLAB Code
    % Generated by MATLAB(R) 7.14 and the DSP System Toolbox 8.2.
    %
    % Generated on: 01-Jul-2012 22:30:29
    %
    
    N  = 20;             % Order
    B  = 1;              % Number of Bands
    F1 = [80 170 1480 2500 5000];  % First Frequency Vector
    A1 = [28 1 2.8 2.8 2.8];     % First Amplitude Vector
    Fs = 10000;          % Sampling Frequency
    
    h = fdesign.arbmag('N,B,F,A', N, B, F1, A1, Fs);
    
    Hd = design(h, 'iirlpnorm');
    
    
    
    % [EOF]
